name: 'GCP Auth Test'

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Or whatever your default branch is

jobs:
  authenticate-and-test:
    runs-on: ubuntu-latest
    
    # These permissions are ESSENTIAL for OIDC
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # Step 1: Standard checkout
    - name: 'Checkout code'
      uses: 'actions/checkout@v4'

    # Step 2: Authenticate to Google Cloud
    # This action logs in and creates a credential file.
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # Step 3: Set up gcloud SDK
    # This action installs gcloud AND configures it to use
    # the credential file created in the step above.
    - name: 'Set up gcloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    # Step 4: Run your gcloud command
    # Now that gcloud is authenticated, this command will work
    # and show your service account as the active user.
    - name: 'Run gcloud command (test)'
      run: |
        echo "Running gcloud auth list..."
        gcloud auth list
