name: 'Image Analysis Workflow'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  image-analysis-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Authenticate and CREATE A CREDENTIAL FILE
      - name: 'Authenticate to Google Cloud'
        id: 'auth' # We give this step an ID to reference its output
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          
          # This is still required to create the file
          create_credentials_file: true

      # Step 2: Set up gcloud SDK
      - name: 'Set up gcloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # Step 3: Configure Docker for Artifact Registry (to pull the image)
      - name: 'Configure Docker for Artifact Registry'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

# Step 4: Run the Scanner Docker Image
      - name: 'Run Image Analysis Scan'
        # This 'run' block is a multi-line shell script.
        # The 'docker run' command below must be one continuous block.
        # Do not add any blank lines or '#' comments between the lines
        # that end with a backslash '\'.
        run: |
          echo "📦 Running container from scanner image..."
          
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ steps.auth.outputs.credentials_file_path }}:/gcp-key.json \
            -e GCLOUD_KEY_PATH=/gcp-key.json \
            -e GCP_PROJECT_ID="cispoc" \
            -e ORGANIZATION_ID="714470867684" \
            -e IMAGE_NAME="alpine" \
            -e IMAGE_TAG="latest" \
            -e CONNECTOR_ID="organizations/714470867684/locations/global/connectors/privatepreviewdemo" \
            -e BUILD_TAG="${{ github.workflow }}" \
            -e BUILD_ID="${{ github.run_number }}" \
            us-central1-docker.pkg.dev/ci-plugin/ci-images/scc-artifactguard-scan-image:latest
