name: 'GCP Auth Test - Anil'

on:
  workflow_dispatch: # This adds the "Run workflow" button

jobs:
  authenticate-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v4'

    # 1. AUTHENTICATE FIRST
    # This step logs you in and creates the credential file.
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # 2. SET UP GCLOUD SECOND
    # This step configures the gcloud tool to use the credentials
    # created by the 'auth' step above.
    - name: 'Set up gcloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    # 3. NOW YOU CAN RUN COMMANDS
    # This will now correctly show the authenticated account.
    - name: 'Run gcloud command (test)'
      run: |
        gcloud auth list
