name: 'GCP Auth Test'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  authenticate-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v4'

    # Step 1: Authenticate to Google Cloud
    - name: 'Authenticate to Google Cloud'
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # Step 2: Set up gcloud SDK
    - name: 'Set up gcloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        # Explicitly set the project for gcloud
        project_id: 'liangyutan-testproject'

    # Step 3: Run gcloud commands
    - name: 'Run gcloud commands to verify'
      run: |
        echo "--- Running gcloud auth list ---"
        gcloud auth list
        
        echo "--- Running gcloud compute instances list ---"
        # This is the real test.
        gcloud compute instances list
